# Generated by Django 4.1 on 2022-09-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_link_alter_project_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default='Sin Subtítulo', max_length=200, verbose_name='Subtítulo'),
        ),
    ]
