# Generated by Django 4.1 on 2022-09-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_avatar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
    ]
