# Generated by Django 4.1 on 2022-09-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_avatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default=333, upload_to='avatares'),
            preserve_default=False,
        ),
    ]
